### ISSUE TITLE
ToDo and Scopes

### ISSUE THREAD

**Issue by itpzzi** [itpzzi/trends-maker#1]
- [ ] declare Scope and ToDo list

---

- [ ] **Orchestrator**
   - [ ] Ask for the search term
   - [ ] Ask for the method
      - [ ] Ask for the prefix
      - [ ] Start Twitter's robot
   - [ ] Start texts' robot
   - [ ] Start Voice Synth robot
   - [ ] Start images' robot
   - [ ] Start video's robot
   - [ ] Start YouTube's robot
   - [ ] Start template's robot

---

- [ ] **Twitter's robot**
   - [ ] OAuth authentication
   - [ ] TrendTopics Scan
   - [ ] Find the relevant word

---

- [ ] **Text robot**
   - [ ] Data structure
   - [ ] Get content of Wikipedia
   - [ ] Clear the content
   - [ ] Break in sentences
   - [ ] Get interpreted information from Watson
   - [ ] Add tags
   - [ ] Save data structure

---

- [ ] **Start Voice Synth robot**
   - [ ] Load data structure
   - [ ] Generate text synthesis
   - [ ] Download the synthesis

---

- [ ] **Images' robot**
   - [ ] Load data structures
   - [ ] Search for images on Google Images
   - [ ] Download images
   - [ ] Save data structure

---

- [ ] **Video's robot**
   - [ ] Photos treatment/Resize images
   - [ ] Create sentences with images
   - [ ] Create video's thumbnail
   - [ ] Render the video with After Effects

---

- [ ] **YouTube's robot**
   - [ ] OAuth authentication
   - [ ] Video upload
   - [ ] Thumbnail upload

---

- [ ] **Template's robot**
   - [ ] Load data structures
   - [ ] Add content to static pages
   - [ ] Save data structure
